name: 01 - Building Blocks

on:
  workflow_dispatch:

jobs:
  echo-hello:
    name: Echo Hello
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    needs: echo-hello
    steps:
      - name: Failed step
        continue-on-error: true
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodbye
        run: echo Goodbye!
